# Generated by Django 5.0.7 on 2024-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_discount_payment_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], max_length=50),
        ),
    ]
